repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.6.1
    hooks:
    -   id: pyupgrade